- name: debug
  hosts: all
  tasks:
    - name: sleep 1800
      shell: while true
              do
                  v=$RANDOM
                  if [ "$v" -gt 16000 ]
                  then
                      echo $v Error
                  else
                      echo $v Good
                  fi
                  sleep 0.1
              done
